import * as fs from "fs/promises";
import * as path from "path";
import type { ParsedArtifacts } from "./artifactParser";
import { componentKey } from "./artifactPaths";

export interface WriteArtifactsOptions {
  workspaceRoot: string;
  docsRelativePath: string;
  flowRelativePath: string;
  specAbsolutePath: string;
  className: string;
  methodName: string;
}

function absFromWorkspaceRoot(workspaceRoot: string, relPosix: string): string {
  const parts = relPosix.split("/").filter((p) => p.length > 0);
  return path.join(workspaceRoot, ...parts);
}

export async function writeParsedArtifacts(
  parsed: ParsedArtifacts,
  opts: WriteArtifactsOptions
): Promise<{ written: string[]; warnings: string[] }> {
  const written: string[] = [];
  const warnings: string[] = [];

  const docAbs = absFromWorkspaceRoot(opts.workspaceRoot, opts.docsRelativePath);
  const flowAbs = absFromWorkspaceRoot(opts.workspaceRoot, opts.flowRelativePath);

  await fs.mkdir(path.dirname(docAbs), { recursive: true });
  await fs.mkdir(path.dirname(flowAbs), { recursive: true });

  const key = componentKey(opts.className, opts.methodName);

  if (parsed.docsMarkdown) {
    await fs.writeFile(docAbs, parsed.docsMarkdown, "utf8");
    written.push(docAbs);
  } else {
    warnings.push("No ### DOCS section found.");
  }

  if (parsed.diagramMermaid) {
    let inner = parsed.diagramMermaid.trim();
    if (inner.startsWith("```")) {
      inner = inner.replace(/^```(?:mermaid)?\s*/iu, "").replace(/```\s*$/u, "").trim();
    }
    const body = `# Flow: ${key}

Generated by NestJS Generator. Unique diagram id: \`${key.replace(/\./gu, "_")}\`

\`\`\`mermaid
${inner}
\`\`\`
`;
    await fs.writeFile(flowAbs, body, "utf8");
    written.push(flowAbs);
  } else {
    warnings.push("No ### DIAGRAM section found.");
  }

  if (parsed.testSnippet) {
    const specPath = opts.specAbsolutePath;
    const banner = `\n\n  // --- nestjs-generator:append:${key} ---\n`;
    const snippet = parsed.testSnippet.trim();
    let specAlreadyThere = false;
    try {
      await fs.access(specPath);
      specAlreadyThere = true;
    } catch {
      specAlreadyThere = false;
    }
    if (specAlreadyThere) {
      const existing = await fs.readFile(specPath, "utf8");
      const next = existing.trimEnd() + banner + snippet + "\n";
      await fs.writeFile(specPath, next, "utf8");
      written.push(specPath);
    } else {
      const header = `/**\n * Tests for ${key}\n * TODO: verify TestingModule imports and providers match your module.\n */\n\n`;
      await fs.writeFile(specPath, header + snippet + "\n", "utf8");
      written.push(specPath);
    }
  } else {
    warnings.push("No ### TEST section found.");
  }

  return { written, warnings };
}
